In [1]:
import kaggle
import pandas as pd
import numpy as np
import sklearn
from sklearn.linear_model import LinearRegression as LR
from sklearn.preprocessing import StandardScaler,LabelEncoder,PolynomialFeatures
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv(r"C:\Users\vamsi\Desktop\champs-scalar-coupling\train.csv")
df2=pd.read_csv(r"C:\Users\vamsi\Desktop\champs-scalar-coupling\test.csv")

In [3]:
df3=df2['id']

In [4]:
dummy=LabelEncoder()
df['type']=dummy.fit_transform(df['type'].astype(str))
df2['type']=dummy.fit_transform(df2['type'].astype(str))
df.columns

Index(['id', 'molecule_name', 'atom_index_0', 'atom_index_1', 'type',
       'scalar_coupling_constant'],
      dtype='object')

In [5]:
df2.shape

(2505542, 5)

In [18]:
x=df[['atom_index_0', 'atom_index_1', 'type']]
y=df[['scalar_coupling_constant']]
xtrain,xtest,ytrain,ytest=train_test_split(polyx,y,test_size=0.3)

In [19]:
model=LR()
model.fit(xtrain,ytrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [20]:
import math
math.sqrt(mean_squared_error(ytest,model.predict(xtest)))

26.80286889752211

In [32]:
nood=model.predict(df2[['atom_index_0', 'atom_index_1', 'type']])

In [34]:
nood.shape

(2505542, 1)

In [35]:
noob=pd.DataFrame(nood)

In [36]:
new=pd.DataFrame(df2['id'])

In [37]:
new['scalar_coupling_constant']=noob

In [43]:
new

              id  scalar_coupling_constant
0        4658147                 31.552442
1        4658148                 52.785946
2        4658149                -10.934424
3        4658150                 52.796681
4        4658151                 31.555234
5        4658152                 52.796681
6        4658153                 -0.304951
7        4658154                 20.924581
8        4658155                 20.920609
9        4658156                 52.803444
10       4658157                 -0.298188
11       4658158                 20.927372
12       4658159                 52.810207
13       4658160                 -0.291426
14       4658161                 -0.276719
15       4658162                 52.809027
16       4658163                 20.932955
17       4658164                 20.928983
18       4658165                 -0.269956
19       4658166                 52.815790
20       4658167                 20.935746
21       4658168                 -0.263193
22       4658169                 52.822553
23       4658170                 52.796681
24       4658171                 31.555234
25       4658172                 31.551262
26       4658173                 20.924581
27       4658174                -10.935604
28       4658175                -10.939576
29       4658176                -10.943548
...          ...                       ...
2505512  7163659                 52.845633
2505513  7163660                 31.604185
2505514  7163661                 -0.259971
2505515  7163662                 -0.263943
2505516  7163663                 31.588299
2505517  7163664                -10.906511
2505518  7163665                -10.914454
2505519  7163666                 -0.237322
2505520  7163667                 31.614920
2505521  7163668                 52.848424
2505522  7163669                 -0.253208
2505523  7163670                 -0.257180
2505524  7163671                 31.595062
2505525  7163672                -10.907691
2505526  7163673                 -0.222615
2505527  7163674                 10.392151
2505528  7163675                 -0.230559
2505529  7163676                 -0.234530
2505530  7163677                 -0.238502
2505531  7163678                 31.609768
2505532  7163679                 52.843272
2505533  7163680                 31.601825
2505534  7163681                -10.900928
2505535  7163682                -21.457300
2505536  7163683                 -0.223796
2505537  7163684                 31.628446
2505538  7163685                 31.624474
2505539  7163686                 -0.239683
2505540  7163687                 31.612559
2505541  7163688                 52.846063

[2505542 rows x 2 columns]

In [46]:
new.to_csv(r"C:\Users\vamsi\Desktop\champs-scalar-coupling\my_1'st_Kaggle.csv",index=False)